name: gofit

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresGoFit
    environment:
      POSTGRES_USER: system_admin
      POSTGRES_PASSWORD: system_admin_password_2024
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_GF:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redisGoFit
    command: sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - redis_data_GF:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_GF:
  redis_data_GF: